name: 'Setup'
description: 'Install Rust Toolchain Components, just, and cross for building on multiple targets.'

runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain || 'stable' }}
        target: ${{ matrix.build-std && 'x86_64-unknown-linux-gnu' || matrix.target }}
        components: ${{ matrix.build-std && 'rust-src' || '' }}

    - name: Install just
      uses: extractions/setup-just@v3

    - name: Install cross
      uses: taiki-e/install-action@v2
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      with:
        tool: cross

    - name: Install cargo-edit
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-edit

    - name: Install patch-crate
      uses: baptiste0928/cargo-install@v3
      with:
        crate: patch-crate

    - name: Install Node.js
      uses: actions/setup-node@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - run: just setup
      shell: bash
